import { AiProduct, type Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";

export function titleFromIdea(idea: string): string {
  const trimmed = idea.trim();
  if (trimmed.length <= 72) return trimmed;
  return `${trimmed.slice(0, 69)}…`;
}

export async function createAdvisorConversation(
  userId: string,
  idea: string,
  analysis: Prisma.InputJsonValue,
) {
  return prisma.aiConversation.create({
    data: {
      userId,
      product: AiProduct.STARTUP_ADVISOR,
      title: titleFromIdea(idea),
      messages: {
        create: [
          { role: "user", content: idea },
          {
            role: "assistant",
            content: "Startup blueprint generated by Mr.Software Advisor.",
            metadata: analysis,
          },
        ],
      },
    },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
    },
  });
}

export async function listUserConversations(userId: string, product?: AiProduct) {
  return prisma.aiConversation.findMany({
    where: { userId, ...(product ? { product } : {}) },
    orderBy: { updatedAt: "desc" },
    take: 20,
    select: {
      id: true,
      title: true,
      product: true,
      createdAt: true,
      updatedAt: true,
      messages: {
        orderBy: { createdAt: "desc" },
        take: 1,
        select: { role: true, content: true, createdAt: true },
      },
    },
  });
}

export async function getUserConversation(userId: string, conversationId: string) {
  return prisma.aiConversation.findFirst({
    where: { id: conversationId, userId },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
    },
  });
}
