import { AiProduct, type Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";

export function titleFromIdea(idea: string): string {
  const trimmed = idea.trim();
  if (trimmed.length <= 72) return trimmed;
  return `${trimmed.slice(0, 69)}…`;
}

export async function createAdvisorConversation(
  userId: string,
  idea: string,
  analysis: Prisma.InputJsonValue,
) {
  return prisma.aiConversation.create({
    data: {
      userId,
      product: AiProduct.STARTUP_ADVISOR,
      title: titleFromIdea(idea),
      messages: {
        create: [
          { role: "user", content: idea },
          {
            role: "assistant",
            content: "Startup blueprint generated by Mr.Software Advisor.",
            metadata: analysis,
          },
        ],
      },
    },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
    },
  });
}

export async function listUserConversations(userId: string, product?: AiProduct) {
  return prisma.aiConversation.findMany({
    where: { userId, ...(product ? { product } : {}) },
    orderBy: { updatedAt: "desc" },
    take: 20,
    select: {
      id: true,
      title: true,
      product: true,
      createdAt: true,
      updatedAt: true,
      messages: {
        orderBy: { createdAt: "desc" },
        take: 1,
        select: { role: true, content: true, createdAt: true },
      },
    },
  });
}

export async function getUserConversation(userId: string, conversationId: string) {
  return prisma.aiConversation.findFirst({
    where: { id: conversationId, userId },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
    },
  });
}

export async function deleteUserConversation(userId: string, conversationId: string) {
  const existing = await prisma.aiConversation.findFirst({
    where: { id: conversationId, userId },
    select: { id: true },
  });
  if (!existing) return false;
  await prisma.aiConversation.delete({ where: { id: conversationId } });
  return true;
}

export async function listCopilotConversations(userId: string, limit = 15) {
  return prisma.aiConversation.findMany({
    where: { userId, product: AiProduct.COPILOT },
    orderBy: { updatedAt: "desc" },
    take: limit,
    select: {
      id: true,
      title: true,
      updatedAt: true,
      messages: {
        orderBy: { createdAt: "desc" },
        take: 1,
        select: { content: true, role: true },
      },
      _count: { select: { messages: true } },
    },
  });
}

export async function getCopilotConversation(userId: string, conversationId: string) {
  return prisma.aiConversation.findFirst({
    where: { id: conversationId, userId, product: AiProduct.COPILOT },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
    },
  });
}

export async function getLatestCopilotConversation(userId: string) {
  return prisma.aiConversation.findFirst({
    where: { userId, product: AiProduct.COPILOT },
    orderBy: { updatedAt: "desc" },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
    },
  });
}

export async function appendCopilotExchange(
  userId: string,
  userMessage: string,
  assistantReply: string,
  conversationId?: string,
) {
  if (conversationId) {
    const existing = await prisma.aiConversation.findFirst({
      where: { id: conversationId, userId, product: AiProduct.COPILOT },
    });
    if (existing) {
      await prisma.aiMessage.createMany({
        data: [
          { conversationId, role: "user", content: userMessage },
          { conversationId, role: "assistant", content: assistantReply },
        ],
      });
      await prisma.aiConversation.update({
        where: { id: conversationId },
        data: { updatedAt: new Date() },
      });
      return existing.id;
    }
  }

  const created = await prisma.aiConversation.create({
    data: {
      userId,
      product: AiProduct.COPILOT,
      title: titleFromIdea(userMessage),
      messages: {
        create: [
          { role: "user", content: userMessage },
          { role: "assistant", content: assistantReply },
        ],
      },
    },
  });
  return created.id;
}

